[SC-89752] create GH actions for ansible-docker-core
quiknode-labs/docker-ansible-core pull request #5
Opened 2024-01-31 06:14 UTC by vignesh-v3

currently we use sjoshi/ansible-core image in almost all of our role-* repositories, this PR would start to push images in the GHCR

we now have the images pushed to [GHCR](https://github.com/quiknode-labs/docker-ansible-core/pkgs/container/docker-ansible-core/versions)

2024-01-31 12:10 UTC, McSim85 requested changes
This is so awesome, that you started to work on this @vignesh-v3 
Overall the recommendation - configure dependabot properly, so it will automatically submit new versions.

2024-01-31 12:10 UTC, McSim85 commented on .github/workflows/docker-image.yml
> +        version: [v2.12, v2.13,v2.15]
```suggestion
        version: [v2.13, v2.15, v2.16]
```

2024-02-01 14:21 UTC, vignesh-v3 commented on .github/workflows/docker-image.yml
> +  LATEST_VERSION: v2.13
its the alpine version

2024-02-01 14:26 UTC, vignesh-v3 commented on .github/workflows/docker-image.yml
> +  LATEST_VERSION: v2.13
@McSim85 the current one which we use here is [v2.13](https://github.com/sjoshi10/docker-ansible-core/blob/main/.github/workflows/ci.yml#L15)

2024-02-07 02:15 UTC, vignesh-v3 commented on .github/workflows/docker-image.yml
> +  LATEST_VERSION: v2.13
updated the ansible to 2.16

2024-02-07 02:53 UTC, sjoshi10 approved these changes
👍

2024-02-07 03:24 UTC, vignesh-v3 commented
> This is so awesome, that you started to work on this @vignesh-v3 Overall the recommendation - configure dependabot properly, so it will automatically submit new versions.

@McSim85 i pushed a minor pip related change to dependabot.yml, please let me know if we're good.

cc: @sjoshi10

2024-02-09 10:40 UTC, McSim85 approved these changes
Guys, I am approving this PR, because the goal of the PR - moving from Saurab account to quicknode.
But, I think, we should revisit this role later to make
- dependabot handle all version upgrades
- remove unused OS like almalinux8, alpine
- RUN instructions can be also revisited and improve multiple apt commands

2024-02-10 03:09 UTC, vignesh-v3 commented
going to merge this, we can open a separate story for the above items.
cc: @sjoshi10

2024-02-10 03:09 UTC, merged